### ISSUE TITLE
The background of these videos

### ISSUE THREAD

**Issue by wangjingbo1219** [ZheC/GTA-IM-Dataset#1]
Hi
Nice Work! 
I want to know if you can provide background pictures for each video(without the person)
Thanks!
Jingbo

**Comment by ZheC** [comment]
Thank you! Now all videos have persons inside the image. In the[ visualization code](https://github.com/ZheC/GTA-IM-Dataset/blob/master/vis_skeleton_pcd.py#L55-L67), we use the instance mask to obtain the depth image without the person. It is possible to obtain the background image using the same method.
