### ISSUE TITLE
Do you also provide camera pose for each frame?

### ISSUE THREAD

**Issue by NagabhushanSN95** [ZheC/GTA-IM-Dataset#11]
Hi,
I'm working on a view synthesis related problem. I am hopeful your dataset might help me. Can you please confirm if you also provide pose (rotation and translation) of the camera for each frame?

Basically, I'm trying to warp a frame to the view of its next frame using camera pose, camera intrinsic matrix and depth map.

Also, it would be good if you can share a sample so that we can try that first and if useful, we can write a mail to you and purchase GTA V.

**Comment by ZheC** [comment]
Thank you for the interest! Yes, we do provide camera pose. See more details in https://github.com/ZheC/GTA-IM-Dataset#dataset-contents. To access the camera pose, use the following code:

import numpy as np
info_npz = np.load(rec_idx+'info_frames.npz'); 
print(info_npz.files)
# the world to camera transformation matrix for frame 0
print(npz['world2cam_trans'][0])

**Comment by NagabhushanSN95** [comment]
Thank you very much for the quick and detailed reply :)
