### ISSUE TITLE
How to know the scene id of each video 

### ISSUE THREAD

**Issue by wangjingbo1219** [ZheC/GTA-IM-Dataset#3]
Hi
I would like to know how to get the scene id of the 30FPS videos because I need to split these videos by scene.
Thanks.
Jingbo

**Comment by Ruitao-L** [comment]
Hi Jingbo,
Did you get replied with the download link of GTA-IM dataset? I sent my request to Zhe several days ago but haven't received replies yet.

**Comment by wangjingbo1219** [comment]
Yes，I have got this dataset for several months.

> Hi Jingbo,
> Did you get replied with the download link of GTA-IM dataset? I sent my request to Zhe several days ago but haven't received replies yet.

**Comment by Ruitao-L** [comment]
Thanks. Guess I'll need more patience then : )

**Comment by Ruitao-L** [comment]
> Yes，I have got this dataset for several months.
> 
> > Hi Jingbo,
> > Did you get replied with the download link of GTA-IM dataset? I sent my request to Zhe several days ago but haven't received replies yet.

Thanks. Guess I'll need more patience then : )

**Comment by ZheC** [comment]
The scene id is in the realtimeinfo.gz in each data folder. Code to load the data:

import pickle
info = pickle.load(open('./realtimeinfo.gz', 'rb'))
