### ISSUE TITLE
Human IDs are different in different images?

### ISSUE THREAD

**Issue by cherryjm** [ZheC/GTA-IM-Dataset#5]
I get the human id as 
https://github.com/ZheC/GTA-IM-Dataset/blob/31d7baaab027cf96ff3465438645ffcdae3d7c1d/vis_skeleton_pcd.py#L62-L64
It is the id at the head location.

It seems that the human id is not unique. Or is it because the head is occluded or out of the field of view?

**Comment by andreaskoelsch** [comment]
I second your problem. This approach of taking the color at the head location is not very stable.

1. It does not work if the head is occluded, as for example in `FPS-5/2020-06-09-16-09-56/00067*`
2. It does not work if the position of the head is incorrect, cf. #6

**Comment by ZheC** [comment]
Yes, the human IDs are different across sequences. To obtain the human ID, we have to use the head position in the image. While this works for most cases, it will have issues when the head is occluded as pointed by @koelscha. A more robust way would be checking the ID of all human joint positions, and use the major one.
